apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: gpu-papermill-execution-complete
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/name: gpu-papermill-execution-complete
    app.kubernetes.io/component: tekton-task
    app.kubernetes.io/version: "1.0.0"
spec:
  description: |
    Complete GPU-accelerated Papermill execution with exact GitHub Actions parameters.
    Executes notebooks using the exact same command line as the original workflow.
  params:
  - name: notebook-relative-dir
    description: Relative directory containing the notebook
    type: string
    default: "notebooks"
  - name: notebook-filename
    description: Notebook filename to execute
    type: string
    default: "01_scRNA_analysis_preprocessing.ipynb"
  - name: output-notebook
    description: Name for the output notebook
    type: string
    default: "01_scRNA_analysis_preprocessing_output.ipynb"
  - name: container-image
    description: Container image to use for execution
    type: string
    default: "nvcr.io/nvidia/rapidsai/notebooks:25.04-cuda12.8-py3.12"
  - name: gpu-count
    description: Number of GPUs to allocate
    type: string
    default: "1"
  - name: memory-limit
    description: Memory limit for the container
    type: string
    default: "16Gi"
  - name: cpu-limit
    description: CPU limit for the container
    type: string
    default: "4"
  workspaces:
  - name: shared-storage
    description: Shared workspace for input/output files
    mountPath: /workspace/shared
  results:
  - name: execution-status
    description: Status of papermill execution
  - name: output-notebook-path
    description: Path to the executed notebook
  - name: papermill-log-path
    description: Path to the papermill execution log
  steps:
  - name: gpu-papermill-execute-complete
    image: $(params.container-image)
    computeResources:
      requests:
        nvidia.com/gpu: 1
        memory: 16Gi
        cpu: 4
      limits:
        nvidia.com/gpu: 1
        memory: 32Gi
        cpu: 8
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
        add: ["IPC_LOCK", "SYS_RESOURCE"]
      runAsNonRoot: false
      runAsUser: 0
      runAsGroup: 0
      seccompProfile:
        type: RuntimeDefault
    env:
    - name: NVIDIA_VISIBLE_DEVICES
      value: "all"
    - name: NVIDIA_DRIVER_CAPABILITIES
      value: "compute,utility"
    - name: WORKSPACE_SHARED_PATH
      value: $(workspaces.shared-storage.path)
    - name: GPU_CACHE_PATH
      value: $(workspaces.shared-storage.path)/gpu-cache
    - name: DOCKER_WRITEABLE_DIR
      value: "/workspace/shared/artifacts"
    - name: NOTEBOOK_RELATIVED_DIR
      value: $(params.notebook-relative-dir)
    - name: NOTEBOOK_FILENAME
      value: $(params.notebook-filename)
    - name: OUTPUT_NOTEBOOK
      value: $(params.output-notebook)
    - name: EXTRA_PIP_PACKAGES
      value: "anndata==0.11.4 array-api-compat==1.12.0 contourpy==1.3.2 cycler==0.12.1 fonttools==4.58.0 h5py==3.13.0 imageio==2.37.0 joblib==1.5.1 kiwisolver==1.4.8 lazy-loader==0.4 legacy-api-wrap==1.4.1 llvmlite==0.44.0 matplotlib==3.10.3 natsort==8.4.0 networkx==3.4.2 numba==0.61.2 numpy==2.2.6 pandas==2.2.3 patsy==1.0.1 pillow==11.2.1 pynndescent==0.5.13 rapids-singlecell==0.12.6 scanpy==1.11.2 scikit-image==0.25.2 scikit-misc==0.5.1 scipy==1.15.3 seaborn==0.13.2 session-info2==0.1.2 statsmodels==0.14.4 threadpoolctl==3.6.0 tifffile==2025.5.10 tqdm==4.67.1 tzdata==2025.2 umap-learn==0.5.7 wget==3.2 deprecated==1.2.18 numcodecs==0.15.1 wrapt==1.17.2 zarr==2.18.7"
    - name: HOME
      value: "/root"
    - name: PATH
      value: "/root/.local/bin:/opt/conda/bin:/usr/local/bin:/usr/bin:/bin"
    - name: CONDA_DEFAULT_ENV
      value: "base"
    volumeMounts:
    - name: dshm
      mountPath: /dev/shm
    script: |
      #!/bin/bash
      set -eu
      
      echo "Starting Complete GPU Papermill Execution (Fixed Environment)..."
      echo "Target notebook: ${NOTEBOOK_RELATIVED_DIR}/${NOTEBOOK_FILENAME}"
      echo "Shared workspace: ${WORKSPACE_SHARED_PATH}"
      echo "GPU cache: ${GPU_CACHE_PATH}"
      
      # Comprehensive permission fixes
      echo "Fixing all permission issues..."
      
      # Fix conda directories - full access
      chown -R root:root /opt/conda 2>/dev/null || echo "WARNING: Cannot change conda ownership"
      chmod -R 755 /opt/conda 2>/dev/null || echo "WARNING: Cannot change conda permissions"
      
      # Fix entire workspace permissions
      chown -R root:root "${WORKSPACE_SHARED_PATH}" 2>/dev/null || echo "WARNING: Cannot change workspace ownership"
      chmod -R 777 "${WORKSPACE_SHARED_PATH}" 2>/dev/null || echo "WARNING: Cannot change workspace permissions"
      
      # Apply Docker Compose compatible memory settings
      echo "Applying Docker Compose compatible memory settings..."
      ulimit -l unlimited 2>/dev/null || echo "WARNING: Cannot set unlimited memlock"
      ulimit -s 67108864 2>/dev/null || echo "WARNING: Cannot set stack size"
      
      # Ensure shared memory is available
      if [ -d "/dev/shm" ]; then
        echo "Shared memory available: $(df -h /dev/shm | tail -1)"
      fi
      
      # Setup environment as root user
      export HOME="/root"
      export USER="root"
      export PATH="/root/.local/bin:/opt/conda/bin:$PATH"
      
      cd "${WORKSPACE_SHARED_PATH}"
      
      # Verify GPU availability
      echo "Checking GPU availability..."
      nvidia-smi --query-gpu=name,memory.total --format=csv,noheader || echo "WARNING: nvidia-smi failed"
      
      # Verify notebook exists
      NOTEBOOK_PATH="${NOTEBOOK_RELATIVED_DIR}/${NOTEBOOK_FILENAME}"
      if [ ! -f "${NOTEBOOK_PATH}" ]; then
        echo "ERROR: Notebook not found: ${NOTEBOOK_PATH}"
        find . -name "*.ipynb" -type f | head -5
        exit 1
      fi
      
      # Create output directories with proper permissions
      mkdir -p "${DOCKER_WRITEABLE_DIR}"
      mkdir -p "${GPU_CACHE_PATH}"
      
      # Fix output directory permissions with full access
      echo "Fixing output directory permissions..."
      chown -R root:root "${DOCKER_WRITEABLE_DIR}" 2>/dev/null || echo "WARNING: Cannot change output dir ownership"
      chmod -R 777 "${DOCKER_WRITEABLE_DIR}" 2>/dev/null || echo "WARNING: Cannot change output dir permissions"
      chown -R root:root "${GPU_CACHE_PATH}" 2>/dev/null || echo "WARNING: Cannot change cache dir ownership"
      chmod -R 777 "${GPU_CACHE_PATH}" 2>/dev/null || echo "WARNING: Cannot change cache dir permissions"
      
      echo "Notebook found: ${NOTEBOOK_PATH}"
      
      # Setup Python environment with proper paths - USE BASE ENVIRONMENT ONLY
      echo "Setting up Python environment..."
      
      # Use base conda environment (the only one that exists)
      PYTHON_BIN="/opt/conda/bin/python"
      PIP_BIN="/opt/conda/bin/pip"
      CONDA_BIN="/opt/conda/bin/conda"
      
      echo "Using base conda environment (only available environment)"
      
      # Verify Python environment
      echo "Python environment verification:"
      $PYTHON_BIN --version && echo "Python OK" || (echo "ERROR: Python failed" && exit 1)
      $PIP_BIN --version && echo "pip OK" || (echo "ERROR: pip failed" && exit 1)
      $CONDA_BIN --version && echo "conda OK" || (echo "ERROR: conda failed" && exit 1)
      
      # Install dependencies with proper permissions
      echo "Installing dependencies..."
      $PIP_BIN install --user --quiet --no-cache-dir papermill ipykernel jupyter || {
        echo "ERROR: Failed to install papermill"
        exit 1
      }
      
      # Install additional packages with conda for better compatibility
      if [ -n "${EXTRA_PIP_PACKAGES:-}" ]; then
        echo "Installing scanpy and other scientific packages..."
        
        # Install scanpy with conda for better compatibility
        $CONDA_BIN install -y -c conda-forge -c bioconda scanpy || {
          echo "WARNING: Conda scanpy failed, trying pip with --user..."
          $PIP_BIN install --user --quiet --no-cache-dir scanpy || echo "WARNING: scanpy installation failed"
        }
        
        # Install other packages with pip using --user to avoid permission issues
        echo "Installing other packages with pip using --user..."
        $PIP_BIN install --user --quiet --no-cache-dir ${EXTRA_PIP_PACKAGES} || echo "WARNING: Some pip packages failed"
        
        # Verify key packages
        echo "Verifying key package installations..."
        $PYTHON_BIN -c "import scanpy as sc; print('SUCCESS: scanpy version:', sc.__version__)" || {
          echo "ERROR: scanpy verification failed"
          echo "Trying to install scanpy again with --user..."
          $PIP_BIN install --user --force-reinstall scanpy
          $PYTHON_BIN -c "import scanpy as sc; print('SUCCESS: scanpy version:', sc.__version__)" || {
            echo "CRITICAL ERROR: scanpy installation completely failed"
            exit 1
          }
        }
        
        $PYTHON_BIN -c "import cupy as cp; print('SUCCESS: cupy GPU count:', cp.cuda.runtime.getDeviceCount())" || echo "WARNING: cupy verification failed"
      fi
      
      # Setup GPU environment
      export CUDA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES:-"all"}
      export CUPY_CACHE_DIR="${GPU_CACHE_PATH}/cupy"
      export NUMBA_CACHE_DIR="${GPU_CACHE_PATH}/numba"
      mkdir -p "${CUPY_CACHE_DIR}" "${NUMBA_CACHE_DIR}"
      
      # Find papermill executable
      PAPERMILL_BIN=""
      if [ -x "/root/.local/bin/papermill" ]; then
        PAPERMILL_BIN="/root/.local/bin/papermill"
      elif [ -x "/opt/conda/bin/papermill" ]; then
        PAPERMILL_BIN="/opt/conda/bin/papermill"
      else
        echo "ERROR: papermill not found after installation"
        exit 1
      fi
      
      # Execute notebook with EXACT GitHub Actions parameters
      echo "Executing notebook with Papermill (GitHub Actions Compatible Parameters)..."
      PAPERMILL_OUTPUT_PATH="${DOCKER_WRITEABLE_DIR}/${OUTPUT_NOTEBOOK}"
      PAPERMILL_LOG_PATH="${DOCKER_WRITEABLE_DIR}/papermill.log"
      
      echo "Command: $PAPERMILL_BIN \"${NOTEBOOK_RELATIVED_DIR}/${NOTEBOOK_FILENAME}\" \"${PAPERMILL_OUTPUT_PATH}\" --log-output --log-level DEBUG --progress-bar --report-mode --kernel python3"
      
      # Execute with EXACT same parameters as GitHub Actions
      PAPERMILL_EXIT_CODE=0
      $PAPERMILL_BIN "${NOTEBOOK_RELATIVED_DIR}/${NOTEBOOK_FILENAME}" "${PAPERMILL_OUTPUT_PATH}" \
          --log-output \
          --log-level DEBUG \
          --progress-bar \
          --report-mode \
          --kernel python3 2>&1 | tee "${PAPERMILL_LOG_PATH}" || PAPERMILL_EXIT_CODE=$?
      
      # Proper error checking
      if [ $PAPERMILL_EXIT_CODE -ne 0 ]; then
        echo "ERROR: Papermill execution failed with exit code: $PAPERMILL_EXIT_CODE"
        echo "Last 30 lines of papermill log:"
        tail -30 "${PAPERMILL_LOG_PATH}" || true
        ls -la "${DOCKER_WRITEABLE_DIR}/" || true
        echo -n "failed" > "$(results.execution-status.path)"
        exit 1
      fi
      
      # Verify output and check for execution errors in the log
      if [ -f "${PAPERMILL_OUTPUT_PATH}" ]; then
        # Check if the log contains execution errors
        if grep -q "PapermillExecutionError" "${PAPERMILL_LOG_PATH}"; then
          echo "ERROR: Papermill execution failed - PapermillExecutionError found in log"
          echo "Last 30 lines of papermill log:"
          tail -30 "${PAPERMILL_LOG_PATH}" || true
          echo -n "failed" > "$(results.execution-status.path)"
          exit 1
        fi
        
        OUTPUT_SIZE=$(du -h "${PAPERMILL_OUTPUT_PATH}" | cut -f1)
        echo "SUCCESS: Output notebook created: ${OUTPUT_SIZE}"
        echo -n "success" > "$(results.execution-status.path)"
        echo -n "${PAPERMILL_OUTPUT_PATH}" > "$(results.output-notebook-path.path)"
        echo -n "${PAPERMILL_LOG_PATH}" > "$(results.papermill-log-path.path)"
      else
        echo "ERROR: Output notebook not found"
        echo -n "failed" > "$(results.execution-status.path)"
        exit 1
      fi
      
      echo "Complete GitHub Actions compatible Papermill execution finished successfully!"
  volumes:
  - name: dshm
    emptyDir:
      medium: Memory
      sizeLimit: 1Gi 