apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: gpu-env-test-fixed
  namespace: tekton-pipelines
  labels:
    test-type: "fixed-version-test"
spec:
  pipelineSpec:
    workspaces:
    - name: shared-artifacts-workspace
    tasks:
    - name: prepare-environment-fixed
      taskRef:
        name: gpu-env-preparation-fixed
      params:
      - name: git-repo-url
        value: "https://github.com/johnnynv/Real-world_Tekton_Installation_Guide.git"
      - name: git-revision
        value: "main"
      - name: verbose
        value: "true"
      workspaces:
      - name: shared-storage
        workspace: shared-artifacts-workspace
  workspaces:
  - name: shared-artifacts-workspace
    persistentVolumeClaim:
      claimName: shared-artifacts-workspace
  timeouts:
    pipeline: "30m" 