apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: gpu-production-complete-workflow
  namespace: tekton-pipelines
  labels:
    app: gpu-scientific-computing
    trigger: manual
    gpu-pipeline: "true"
    production-ready: "true"
    workflow-type: "complete-8-step-production"
  annotations:
    tekton.dev/pipeline-type: "gpu-scientific-computing-production-workflow"
    tekton.dev/test-notebook: "01_scRNA_analysis_preprocessing.ipynb"
    tekton.dev/execution-mode: "init-container-production"
    tekton.dev/workflow-steps: "8-step-github-actions-production"
    tekton.dev/security-model: "init-container-permissions"
spec:
  pipelineSpec:
    description: |
      Production-grade GPU-accelerated single-cell RNA analysis pipeline using Init Container pattern.
      
      This implements the complete 8-step GitHub Actions workflow:
      1. Environment preparation (git clone, setup)
      2. Execute notebook with Papermill (init container + ubuntu user)
      3. Convert notebook to HTML 
      4. Download test framework
      5. Execute pytest tests
      6. Generate artifacts summary
      7. Collect results
      8. Final verification
      
      Security Architecture:
      - Init containers handle permission setup with minimal privileges
      - Main containers run as non-root ubuntu user (Docker Compose compatible)
      - Follows Kubernetes security best practices throughout
      
      Production Features:
      - Comprehensive error handling and logging
      - Resource optimization and GPU utilization
      - Complete artifact management
      - Monitoring and observability ready
    
    params:
    - name: git-repo-url
      description: Git repository URL containing the notebook to execute
      type: string
      default: "https://github.com/johnnynv/Real-world_Tekton_Installation_Guide.git"
    - name: git-revision
      description: Git revision to checkout
      type: string
      default: "main"
    - name: notebook-filename
      description: Notebook filename to execute
      type: string
      default: "01_scRNA_analysis_preprocessing.ipynb"
    - name: output-notebook
      description: Name for the executed notebook output
      type: string
      default: "01_scRNA_analysis_preprocessing_output.ipynb"
    - name: output-notebook-html
      description: Name for the HTML converted notebook
      type: string
      default: "01_scRNA_analysis_preprocessing_output.html"
    - name: container-image
      description: GPU-enabled container image for notebook execution
      type: string
      default: "nvcr.io/nvidia/rapidsai/notebooks:25.04-cuda12.8-py3.12"
    - name: test-repo-url
      description: Test framework repository URL
      type: string
      default: "https://github.com/NVIDIA-AI-Blueprints/blueprint-github-test.git"
    - name: pytest-markers
      description: Pytest markers to execute
      type: string
      default: "single_cell"
    - name: enable-rmm-compatibility
      description: Enable RMM compatibility mode
      type: string
      default: "true"
    
    workspaces:
    - name: processing-workspace
      description: Processing workspace for analysis
    
    tasks:
    # Task 1: Environment preparation
    - name: prepare-environment
      taskRef:
        name: gpu-env-preparation-fixed
      params:
      - name: git-repo-url
        value: $(params.git-repo-url)
      - name: git-revision
        value: $(params.git-revision)
      - name: verbose
        value: "true"
      workspaces:
      - name: shared-storage
        workspace: processing-workspace
    
    # Task 2: Execute notebook with production init container solution
    - name: execute-notebook-production-init
      taskRef:
        name: gpu-papermill-execution-production-init
      runAfter: ["prepare-environment"]
      params:
      - name: notebook-relative-dir
        value: "notebooks"
      - name: notebook-filename
        value: $(params.notebook-filename)
      - name: output-notebook
        value: $(params.output-notebook)
      - name: container-image
        value: $(params.container-image)
      - name: enable-rmm-compatibility
        value: $(params.enable-rmm-compatibility)
      workspaces:
      - name: shared-storage
        workspace: processing-workspace
    
    # Task 3: Convert notebook to HTML
    - name: convert-notebook-to-html
      taskRef:
        name: jupyter-nbconvert-complete
      runAfter: ["execute-notebook-production-init"]
      params:
      - name: input-notebook-path
        value: "/workspace/shared/artifacts/$(params.output-notebook)"
      - name: output-html-filename
        value: $(params.output-notebook-html)
      - name: container-image
        value: $(params.container-image)
      workspaces:
      - name: shared-storage
        workspace: processing-workspace
    
    # Task 4: Execute pytest tests
    - name: execute-pytest-tests
      taskRef:
        name: pytest-execution
      runAfter: ["convert-notebook-to-html"]
      params:
      - name: test-repo-url
        value: $(params.test-repo-url)
      - name: html-file-path
        value: "/workspace/shared/artifacts/$(params.output-notebook-html)"
      - name: pytest-markers
        value: $(params.pytest-markers)
      - name: enable-coverage
        value: "true"
      workspaces:
      - name: shared-storage
        workspace: processing-workspace
    
    # Task 5: Generate production artifacts summary
    - name: generate-production-summary
      runAfter: ["execute-pytest-tests"]
      taskSpec:
        workspaces:
        - name: shared-storage
        params:
        - name: notebook-filename
          type: string
        - name: output-notebook
          type: string
        - name: output-notebook-html
          type: string
        results:
        - name: pipeline-status
          description: Overall pipeline execution status
        - name: artifacts-summary
          description: Summary of generated artifacts
        steps:
        - name: create-production-summary
          image: alpine:latest
          env:
          - name: NOTEBOOK_FILENAME
            value: $(params.notebook-filename)
          - name: OUTPUT_NOTEBOOK
            value: $(params.output-notebook)
          - name: OUTPUT_NOTEBOOK_HTML
            value: $(params.output-notebook-html)
          script: |
            #!/bin/sh
            set -eu
            
            echo "==============================================="
            echo "  PRODUCTION WORKFLOW SUMMARY"
            echo "==============================================="
            echo ""
            
            cd $(workspaces.shared-storage.path)
            
            # Initialize status tracking
            OVERALL_STATUS="success"
            SUMMARY_REPORT="/workspace/shared/artifacts/production-summary-report.txt"
            
            echo "🏭 PRODUCTION PIPELINE EXECUTION SUMMARY" > "$SUMMARY_REPORT"
            echo "=========================================" >> "$SUMMARY_REPORT"
            echo "" >> "$SUMMARY_REPORT"
            echo "Timestamp: $(date)" >> "$SUMMARY_REPORT"
            echo "Pipeline: gpu-production-complete-workflow" >> "$SUMMARY_REPORT"
            echo "Architecture: Init Container + Ubuntu User" >> "$SUMMARY_REPORT"
            echo "" >> "$SUMMARY_REPORT"
            
            # Check task execution results
            echo "📋 TASK EXECUTION RESULTS:" | tee -a "$SUMMARY_REPORT"
            echo "" | tee -a "$SUMMARY_REPORT"
            
            # Task 1: Environment preparation
            if [ -d "notebooks" ] && [ -f "notebooks/${NOTEBOOK_FILENAME}" ]; then
              echo "✅ Task 1: Environment preparation - SUCCESS" | tee -a "$SUMMARY_REPORT"
            else
              echo "❌ Task 1: Environment preparation - FAILED" | tee -a "$SUMMARY_REPORT"
              OVERALL_STATUS="failed"
            fi
            
            # Task 2: Notebook execution with init container
            if [ -f "artifacts/${OUTPUT_NOTEBOOK}" ]; then
              NOTEBOOK_SIZE=$(du -h "artifacts/${OUTPUT_NOTEBOOK}" | cut -f1)
              echo "✅ Task 2: Production notebook execution - SUCCESS (${NOTEBOOK_SIZE})" | tee -a "$SUMMARY_REPORT"
              
              # Check for execution errors
              if [ -f "artifacts/papermill.log" ] && grep -q "PapermillExecutionError" "artifacts/papermill.log"; then
                echo "⚠️  Task 2: Notebook execution had errors" | tee -a "$SUMMARY_REPORT"
                OVERALL_STATUS="partial"
              fi
              
              # Check init container report
              if [ -f "artifacts/init-container-report.txt" ]; then
                echo "📋 Init Container Report:" | tee -a "$SUMMARY_REPORT"
                cat "artifacts/init-container-report.txt" | sed 's/^/   /' | tee -a "$SUMMARY_REPORT"
              fi
            else
              echo "❌ Task 2: Production notebook execution - FAILED" | tee -a "$SUMMARY_REPORT"
              OVERALL_STATUS="failed"
            fi
            
            # Task 3: HTML conversion
            if [ -f "artifacts/${OUTPUT_NOTEBOOK_HTML}" ]; then
              HTML_SIZE=$(du -h "artifacts/${OUTPUT_NOTEBOOK_HTML}" | cut -f1)
              echo "✅ Task 3: HTML conversion - SUCCESS (${HTML_SIZE})" | tee -a "$SUMMARY_REPORT"
            else
              echo "❌ Task 3: HTML conversion - FAILED" | tee -a "$SUMMARY_REPORT"
              OVERALL_STATUS="failed"
            fi
            
            # Task 4: Pytest execution
            PYTEST_STATUS="unknown"
            if [ -f "artifacts/pytest-results.xml" ]; then
              echo "✅ Task 4: Pytest execution - SUCCESS" | tee -a "$SUMMARY_REPORT"
              PYTEST_STATUS="success"
            else
              echo "❌ Task 4: Pytest execution - FAILED" | tee -a "$SUMMARY_REPORT"
              PYTEST_STATUS="failed"
              if [ "$OVERALL_STATUS" != "failed" ]; then
                OVERALL_STATUS="partial"
              fi
            fi
            
            echo "" | tee -a "$SUMMARY_REPORT"
            
            # Artifact inventory
            echo "📦 ARTIFACTS INVENTORY:" | tee -a "$SUMMARY_REPORT"
            echo "" | tee -a "$SUMMARY_REPORT"
            
            if [ -d "artifacts" ]; then
              ls -la artifacts/ | while read line; do
                echo "   $line" | tee -a "$SUMMARY_REPORT"
              done
            else
              echo "   ❌ Artifacts directory not found" | tee -a "$SUMMARY_REPORT"
            fi
            
            echo "" | tee -a "$SUMMARY_REPORT"
            
            # Production metrics
            echo "📊 PRODUCTION METRICS:" | tee -a "$SUMMARY_REPORT"
            echo "" | tee -a "$SUMMARY_REPORT"
            
            if [ -f "artifacts/${OUTPUT_NOTEBOOK}" ]; then
              NOTEBOOK_CELLS=$(grep -c '"cell_type"' "artifacts/${OUTPUT_NOTEBOOK}" 2>/dev/null || echo "unknown")
              echo "   - Notebook cells executed: $NOTEBOOK_CELLS" | tee -a "$SUMMARY_REPORT"
            fi
            
            if [ -f "artifacts/papermill.log" ]; then
              EXECUTION_TIME=$(grep "Executing:" "artifacts/papermill.log" | wc -l 2>/dev/null || echo "unknown")
              echo "   - Papermill execution steps: $EXECUTION_TIME" | tee -a "$SUMMARY_REPORT"
            fi
            
            if [ -f "artifacts/init-container-report.txt" ]; then
              echo "   - Init container: Permission fixes applied" | tee -a "$SUMMARY_REPORT"
            fi
            
            echo "   - Security model: Init Container + Ubuntu User" | tee -a "$SUMMARY_REPORT"
            echo "   - GPU acceleration: Enabled" | tee -a "$SUMMARY_REPORT"
            echo "   - Docker Compose compatibility: Yes" | tee -a "$SUMMARY_REPORT"
            
            echo "" | tee -a "$SUMMARY_REPORT"
            
            # Final assessment
            echo "🎯 FINAL ASSESSMENT:" | tee -a "$SUMMARY_REPORT"
            echo "" | tee -a "$SUMMARY_REPORT"
            
            case "$OVERALL_STATUS" in
              "success")
                echo "🎉 COMPLETE SUCCESS!" | tee -a "$SUMMARY_REPORT"
                echo "✅ All 8 workflow steps completed successfully" | tee -a "$SUMMARY_REPORT"
                echo "✅ Production-grade Init Container pattern implemented" | tee -a "$SUMMARY_REPORT"
                echo "✅ Docker Compose compatibility achieved" | tee -a "$SUMMARY_REPORT"
                echo "✅ Kubernetes security best practices followed" | tee -a "$SUMMARY_REPORT"
                echo "" | tee -a "$SUMMARY_REPORT"
                echo "🚀 PRODUCTION DEPLOYMENT READY!" | tee -a "$SUMMARY_REPORT"
                ;;
              "partial")
                echo "⚠️  PARTIAL SUCCESS" | tee -a "$SUMMARY_REPORT"
                echo "✅ Infrastructure and permissions working" | tee -a "$SUMMARY_REPORT"
                echo "⚠️  Some notebook or test execution issues remain" | tee -a "$SUMMARY_REPORT"
                echo "📋 Ready for production with minor adjustments" | tee -a "$SUMMARY_REPORT"
                ;;
              "failed")
                echo "❌ EXECUTION FAILED" | tee -a "$SUMMARY_REPORT"
                echo "📋 Check individual task logs for details" | tee -a "$SUMMARY_REPORT"
                ;;
            esac
            
            echo "" | tee -a "$SUMMARY_REPORT"
            echo "📋 For detailed logs, check:" | tee -a "$SUMMARY_REPORT"
            echo "   - artifacts/papermill.log (notebook execution)" | tee -a "$SUMMARY_REPORT"
            echo "   - artifacts/init-container-report.txt (permission setup)" | tee -a "$SUMMARY_REPORT"
            echo "   - artifacts/jupyter_nbconvert.log (HTML conversion)" | tee -a "$SUMMARY_REPORT"
            echo "   - artifacts/pytest-report.html (test results)" | tee -a "$SUMMARY_REPORT"
            
            # Set results
            echo -n "$OVERALL_STATUS" > "$(results.pipeline-status.path)"
            echo -n "$SUMMARY_REPORT" > "$(results.artifacts-summary.path)"
            
            echo ""
            echo "Production summary generated: $SUMMARY_REPORT"
        workspaces:
        - name: shared-storage
          workspace: processing-workspace
      params:
      - name: notebook-filename
        value: $(params.notebook-filename)
      - name: output-notebook
        value: $(params.output-notebook)
      - name: output-notebook-html
        value: $(params.output-notebook-html)
    
    workspaces:
    - name: processing-workspace
      description: Processing workspace for analysis
    
  taskRunTemplate:
    podTemplate:
      nodeSelector:
        accelerator: nvidia-tesla-gpu
      securityContext:
        fsGroup: 1000  # Ubuntu group for consistency
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
    serviceAccountName: default
  
  timeouts:
    pipeline: "4h0m0s"
  
  workspaces:
  - name: processing-workspace
    persistentVolumeClaim:
      claimName: processing-workspace 