apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-restricted-user
  namespace: tekton-pipelines
  labels:
    app: tekton-dashboard
    component: rbac
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-restricted-viewer
  labels:
    app: tekton-dashboard
    component: rbac
rules:
# Pipeline permissions - read only
- apiGroups: ["tekton.dev"]
  resources: ["pipelines", "pipelineruns"]
  verbs: ["get", "list", "watch"]

# Task permissions - read only  
- apiGroups: ["tekton.dev"]
  resources: ["tasks", "taskruns", "clustertasks"]
  verbs: ["get", "list", "watch"]

# EventListener permissions - read only
- apiGroups: ["triggers.tekton.dev"]
  resources: ["eventlisteners", "triggers", "triggerbindings", "triggertemplates"]
  verbs: ["get", "list", "watch"]

# Basic Kubernetes resources for dashboard functionality
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]

# Required for dashboard to function (excluding secrets for security)
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]

# Namespace access
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-restricted-user-binding
  labels:
    app: tekton-dashboard
    component: rbac
subjects:
- kind: ServiceAccount
  name: tekton-restricted-user
  namespace: tekton-pipelines
roleRef:
  kind: ClusterRole
  name: tekton-restricted-viewer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: tekton-restricted-user-token
  namespace: tekton-pipelines
  labels:
    app: tekton-dashboard
    component: rbac
  annotations:
    kubernetes.io/service-account.name: tekton-restricted-user
type: kubernetes.io/service-account-token